Repository USB-CI3715/nodebb-usb-24-digitalpioneers, pull requests merged in 2024-11, with the labels that each got.

#26 ✅ Funcionalidad: Report de Mensaje en el chat
  public/src/client/chats.js
  src/views/partials/chats/message.tpl
Labels: interface, button, easy

#25 Elloquius - Añadir funcionalidad de guardar comentarios
  plugins/nodebb-plugin-save-comment/library.js
  plugins/nodebb-plugin-save-comment/package.json
  plugins/nodebb-plugin-save-comment/plugin.json
  plugins/nodebb-plugin-save-comment/templates/partials/topic/post-menu-list.tpl
  plugins/nodebb-plugin-save-comment/templates/partials/topic/post-menu.tpl
  plugins/nodebb-plugin-save-comment/templates/partials/topic/post.tpl
  plugins/nodebb-plugin-save-comment/templates/partials/topics_list.tpl
  plugins/nodebb-plugin-save-comment/templates/topic.tpl
Labels: interface, button

#27 simulator starred and unstarred message
  plugins/nodebb-plugin-highlight-post-button/library.js
  plugins/nodebb-plugin-highlight-post-button/package.json
  plugins/nodebb-plugin-highlight-post-button/plugin.json
  plugins/nodebb-plugin-highlight-post-button/templates/partials/topic/post.tpl
  public/src/client/topic/postTools.js
Labels: enhancement, interface, button, easy

#23 Agregar select rol a interfaz de registro
  src/views/registerComplete.tpl
Labels: interface, easy

#28 Agrega el plugin nodebb-plugin-like-dislike en la carpeta plugins
  plugins/nodebb-plugin-like-dislike/library.js
  plugins/nodebb-plugin-like-dislike/package.json
  plugins/nodebb-plugin-like-dislike/plugin.json
  plugins/nodebb-plugin-like-dislike/templates/partials/topic/post-menu-list.tpl
  plugins/nodebb-plugin-like-dislike/templates/partials/topic/post-menu.tpl
  plugins/nodebb-plugin-like-dislike/templates/partials/topic/post.tpl
  plugins/nodebb-plugin-like-dislike/templates/partials/topics_list.tpl
  plugins/nodebb-plugin-like-dislike/templates/topic.tpl
Labels: enhancement, button

#29 Agrega contadores de like y dislike
  plugins/nodebb-plugin-like-dislike/templates/partials/topic/post.tpl
  public/language/en-GB/global.json
  public/language/en-GB/topic.json
  public/language/en-US/global.json
  public/language/en-US/topic.json
  public/language/es/topic.json
  public/src/client/topic/events.js
  public/src/client/topic/postTools.js
  public/src/client/topic/votes.js
  public/src/modules/components.js
Labels: moderate, button

#30 Integra los plugins save-comment, highlight-comment y like-dislike en el plugin digitalpioneers
  plugins/nodebb-plugin-digitalpioneers/library.js
  plugins/nodebb-plugin-digitalpioneers/package.json
  plugins/nodebb-plugin-digitalpioneers/plugin.json
  plugins/nodebb-plugin-digitalpioneers/templates/partials/topic/post-menu-list.tpl
  plugins/nodebb-plugin-digitalpioneers/templates/partials/topic/post-menu.tpl
  plugins/nodebb-plugin-digitalpioneers/templates/partials/topic/post.tpl
  plugins/nodebb-plugin-digitalpioneers/templates/partials/topics_list.tpl
  plugins/nodebb-plugin-digitalpioneers/templates/topic.tpl
Labels: enhancement, easy

#33 add answered question button in interface
  plugins/nodebb-plugin-digitalpioneers/templates/partials/topics_list.tpl
Labels: enhancement, interface, button, easy

#36 Implementar checkbox para rol profesor
  plugins/nodebb-plugin-digitalpioneers/templates/register.tpl
  public/language/en-GB/register.json
  public/language/en-US/register.json
  public/language/es/register.json
  src/user/create.js
  src/views/registerComplete.tpl
Labels: interface, moderate, button, backend

#39 Muestra rol en perfil
  plugins/nodebb-plugin-digitalpioneers/templates/account/profile.tpl
  plugins/nodebb-plugin-digitalpioneers/templates/partials/account/header.tpl
  public/language/en-GB/user.json
  public/language/en-US/user.json
  public/language/es/user.json
Labels: interface, easy

#38 Implementa nuevos tests para las nuevas funcionalidades
  .github/workflows/test.yaml
  UserGuide.md
  dump.rdb
  public/src/client/topic/events.js
  src/dummy.js
  src/user/reset.js
  src/user/topics.js
  test/digitalpioneers/events.js
Labels: high, automatic testing
